# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161110_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='parent_user',
            new_name='parent',
        ),
    ]
