# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161110_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('post', models.CharField(max_length=250, verbose_name='Посада')),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('middle_name', models.CharField(max_length=50, verbose_name='По-батькові')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.User', verbose_name='Керівник')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
