# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20161111_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='meter_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.MeterType', verbose_name='Тип лічильника'),
            preserve_default=False,
        ),
    ]
