# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_meter_meter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name_plural': 'Категорії',
                'verbose_name': 'Категорія',
            },
        ),
        migrations.CreateModel(
            name='ObjectPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Призначення об'єкту")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name_plural': "Призначення об'єктів",
                'verbose_name': "Призначення об'єкта",
            },
        ),
        migrations.AddField(
            model_name='building',
            name='date_from',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата здачі в експлуатацію'),
        ),
        migrations.AddField(
            model_name='building',
            name='square',
            field=models.IntegerField(default=1, verbose_name='Площа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='purpose',
            field=models.ManyToManyField(to='base.ObjectPurpose', verbose_name="Призначення об'єкта"),
        ),
    ]
