# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20161114_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Category', verbose_name='Категорія'),
            preserve_default=False,
        ),
    ]
