# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Від')),
                ('date_until', models.DateField(verbose_name='До')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Кількість використаних одиниць')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Building', verbose_name='Будівля')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Institution', verbose_name='Заклад')),
                ('meter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MeterType', verbose_name='Тип лічильника')),
            ],
            options={
                'verbose_name': 'Рахунок',
                'verbose_name_plural': 'Рахунки',
            },
        ),
    ]
