# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Кількість')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Building', verbose_name='Заклад')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва')),
                ('unit', models.CharField(max_length=100, verbose_name='Одиниця виміру')),
            ],
            options={
                'verbose_name': 'Тип характеристики',
                'verbose_name_plural': 'Типи характеристик',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Відсоток від загальної кількості')),
                ('date_from', models.DateField(verbose_name='Від')),
                ('date_until', models.DateField(blank=True, null=True, verbose_name='До')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Component', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ComponentType', verbose_name='Тип компоненту')),
            ],
            options={
                'verbose_name': 'Тип Характеристики',
                'verbose_name_plural': 'Типи характеристик',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.FeatureType', verbose_name='Тип характеристики'),
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ComponentType', verbose_name='Тип'),
        ),
    ]
