# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20161114_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'permissions': (('view_buildings', 'View buildings'),), 'verbose_name': 'Будівля', 'verbose_name_plural': 'Будівлі'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненти'},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={'verbose_name': 'Тип компоненту', 'verbose_name_plural': 'Типи компонентів'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'permissions': (('view_institution', 'View institutions'),), 'verbose_name': 'Заклад, установа', 'verbose_name_plural': 'Заклади, установи'},
        ),
    ]
