# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20161114_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Від'),
        ),
    ]
