# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20161114_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'permissions': (('view_building', 'Переглядати будівлі'), ('lead_building', 'Керувати будівлями'), ('create_building', 'Створювати будівлі')), 'verbose_name': 'Будівля', 'verbose_name_plural': 'Будівлі'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'permissions': (('view_institution', 'Переглядати заклади'), ('lead_institution', 'Керувати закладами'), ('create_institution', 'Створювати заклади')), 'verbose_name': 'Заклад, установа', 'verbose_name_plural': 'Заклади, установи'},
        ),
    ]
