# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20161116_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Building', verbose_name='Будівля'),
        ),
    ]
