# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20161121_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('create_objects', "Створювати об'єкти"), ('create_components', 'Створювати компоненти'), ('delegate_permissions', 'Делегувати повноваження'), ('invite_users', 'Запрошувати користувачів')), 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
