# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20161121_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today),
        ),
    ]
