# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_building_floor_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Назва закладу'),
        ),
        migrations.AlterField(
            model_name='metertype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тип лічильника'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set([('name', 'institution')]),
        ),
        migrations.AlterUniqueTogether(
            name='featuretype',
            unique_together=set([('component_type', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together=set([('name', 'institution', 'building', 'meter_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='objectpurpose',
            unique_together=set([('name', 'category')]),
        ),
    ]
