# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20161125_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('category', 'meter_type', 'price')]),
        ),
    ]
